name: Create Pull Request

on:
  push:
    branches:
      - 'dev'
    paths-ignore:
      - '.github/**'

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get commit message
        id: extract_commit
        run: |
          echo "commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
          if [[ "${{ env.commit_message }}" != *"[pull-request]"* ]]; then
            echo "No '[pull-request]' in commit message, skipping PR creation."
            exit 0
          fi

      - name: Gather commit messages
        id: commits
        run: |
          COMMITS=$(git log origin/main..HEAD --oneline)
          echo "commits_body=$COMMITS" >> $GITHUB_ENV

      - name: Determine PR title
        id: determine_pr_title
        run: |
          PR_TITLE="Automated PR from ${{ github.ref_name }}"
          if [[ "${{ env.commit_message }}" == *"[major]"* ]]; then
            PR_TITLE="$PR_TITLE [major]"
          elif [[ "${{ env.commit_message }}" == *"[minor]"* ]]; then
            PR_TITLE="$PR_TITLE [minor]"
          fi
          echo "pr_title=$PR_TITLE" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: ${{ github.ref_name }}
          title: ${{ env.pr_title }}
          body: |
            ### Commits included in this PR:
            ${{ env.commits_body }}